GET http://localhost:8080/api/v1/user/1

###

GET http://localhost:8080/rest/v1/user/6

###

GET https://api.openapi-generator.tech/api/gen/clients

###
POST /rest/v1/user/add HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Content-Length: 41

{
  "password": "EXAMPLE_PASSWORD",
  "login": "EXAMPLE_LOGIN"
}