spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/m5l9
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp